### ISSUE TITLE
Add more colors to the color selector

### ISSUE THREAD

**Issue by brycethorup** [brycethorup/create-a-hero-tracker#1]
Gray - (hex value here)
Dark Orange - (hex value here)
Dark Green - (hex value here)
Dark Blue - (hex value here)

**Comment by sephirob** [comment]
GRAY:
High: C6C6C6
Mid: 7C7C7C
Shad: 515151

DARK ORANGE:
High: ED7D03
Mid: C16900
Shad: 7A4000

DARK GREEN:
High: 1AD100
Mid: 0A8C00
Shad: 0E5E00

DARK BLUE: 
High: 0057D6
Mid: 023A93
Shad: 012359
