### ISSUE TITLE
Create recording screen graphic

### ISSUE THREAD

**Issue by brycethorup** [brycethorup/create-a-hero-tracker#14]
Replace the current implementation with a static graphic with fonts converted to objects.

**Comment by sephirob** [comment]
Lower right button placement shuffled, Start Over button made, otherwise if all fonts are just Comic Sans, finished.

**Comment by sephirob** [comment]
Updated in full with a progress bar for the seconds remaining, as well as a Reporter character to liven things up. The reporter Character will help provide the identity/reason for the play back when it has audio frames.
